### ISSUE TITLE
handle the overflow of the CYCCNT

### ISSUE THREAD

**Issue by flagyan** [esynr3z/profiler-cortex-m4#1]
The CYCCNT is a 32bit register and so it will overflow if the events accumulately take long time and then the profiler will output invalid data, i.e., for the 180M clock on stm32f469, the maximum duration is 2^32/18e6=23.86 seconds. It's better to add other timers, i.e., the RTC timer, in the profiler code to handle this overflow.

**Comment by esynr3z** [comment]
Of course, there are plenty things to improve. But the main goal was to create some simple vendor-independent tool. Use of any other timer outside of the Cortex-M core will create dependencies that I want to avoid.
